image: openjdk:12-jdk-alpine

stages:
  - build

variables:
  MONGO_HOST: 'mongo'

before_script:
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build

  services:
    - mongo:4.2
  script:
    - ./gradlew build
