image: openjdk:12-jdk-alpine

stages:
  - build

before_script:
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build
