version: '3.7' # compose file format version

services:
  mongodb:
    image: mongo:4.2
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
#    driver: local-persist
#    driver_opts:
#      mountpoint: ./data